### ISSUE TITLE
Recover labels from fused dynamic points

### ISSUE THREAD

**Issue by finnSartoris** [JulesSanchez/recoverKITTI360label#2]
Does the script also serve to recover the labels from the fused dynamic points?

**Comment by JulesSanchez** [comment]
Hi,

I apologize but I don't understand what points you're referring to.
A quick explanation of how it works : 
Following the original C++ script, I recover the position of each individual frame (one sweep) in the global coordinates (which is the coordinate system of the accumulated labelized point clouds). The accumulated point cloud is subsampled, so there is not a one to one match between the scans and the accumulated point cloud. So what is done is registering the scan and applying a radius search for each point (in the scan) inside the accumulated point cloud. Based on the found neighbors we recover the label.

Hopefully the full explanation of the process helps you answer your question. Otherwise feel free to enlighten me about what are the fused dynamic points.

Jules

**Comment by finnSartoris** [comment]
Thanks for your quick and detailed explanation. 

By dynamic fused points I mean the data that is in the Kitti360 folder structure under data_3d_semantics/train/2013_05_28_drive_{seq:0>4}_sync/**dynamic**/{start_frame:0>10}_{end_frame:0>10}.ply. 
In the Script so far only the data from data_3d_semantics/train/2013_05_28_drive_{seq:0>4}_sync/**static**/{start_frame:0>10}_{end_frame:0>10}.ply are used (see line 13 in recoverLabels.py and line 31 in accumulation.py), my question was aimed at whether the script can also be used with the data in the dynamic folder, or whether that makes a difference.

Probably it comes down to the same thing since the dynamic folder has no further content for each point except for the timestamps.

**Comment by JulesSanchez** [comment]
Oh ok, I forgot about them. At the moment it only works on static point cloud then.
But a minimal adaption could be applied to the code that it can handle dynamic point cloud and retrieve the timestamps along with the thanks to the exact same procedure. I'm not sure how helpful it would be though.

**Comment by finnSartoris** [comment]
My thoughts were that if only the labels of the static points are recovered, then the dynamic objects that are present in the raw velodyne data would be incorrectly labeled.
For example, the points of a dynamic object, such as a car moving on a road, would then be incorrectly labeled (e.g. incorrectly as a road, at least the tires), since the dynamic points are left out of the recovery and the nearest neighbor algorithm cannot correctly assign these points from the raw data due to the missing labels of the dynamic points.

**Comment by JulesSanchez** [comment]
There can definitely incorrect points, especially at interface levels. But sometimes it also stems directly from the annotation, so I didn't look too much into it. You could do a two step retrieval by first doing dynamic and then doing static if you assume it would be better.
I didn't inspect the dynamic pointcloud at all so I lack knowledge about it but static pointcloud looked like all points were labelized

**Comment by finnSartoris** [comment]
I do have one last question, though. When looking at the recovered labels, I noticed that sometimes a label of -1 is recovered, whereas in the supplied labels (data_3d_semantics/train/...) no point with the label -1 appears. I am already trying to find out where this -1 comes from, but I would appreciate a hint. I guess that a -1 means that no nearest neighbor could be found and thus in the writeLabelsToFolder function the -1 remains as label.
Thanks a lot!

**Comment by JulesSanchez** [comment]
Yes -1 means no information indeed ! There are several occurrences cases such as points too far, but also sometimes part of the scenes that were removed (especially extremities of the aggregated point clouds)
